export {default as Navbar} from './Navbar/Navbar'
export {default as FAQs} from './FAQs/FAQs'
export {default as Footer} from './Footer/Footer'
export {default as Layout} from './Layout/Layout'
export {default as Testimonials} from './Testimonials/Testimonials'
export {default as Team} from './Team/Team'